//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class T_Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Categories()
        {
            this.T_Products = new HashSet<T_Products>();
        }


        [Display(Name = "آیدی")]
        public int Id { get; set; }


        [Display(Name = "نام دسته بندی ")]
        public string CategoryName { get; set; }

        [Display(Name = "مدیر ثبت کننده")]
        public Nullable<int> RegisterAdminId { get; set; }
    
        public virtual T_Admins T_Admins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Products> T_Products { get; set; }
    }
}
