//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class T_Products
    {

        [Display(Name = "آیدی")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        public int Id { get; set; }



        [Display(Name = "دسته بندی")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = " {0} باید حداقل 2 و حداکثر 30 کاراکتر باشد")]
        public string CategoryName { get; set; }


        [Display(Name = "برند")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = " {0} باید حداقل 2 و حداکثر 30 کاراکتر باشد")]
        public string BrandName { get; set; }



        [Display(Name = "مدل")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = " {0} باید حداقل 2 و حداکثر 30 کاراکتر باشد")]
        public string ModelName { get; set; }



        [Display(Name = "توضیحات")]
        [StringLength(100, MinimumLength = 2, ErrorMessage = " {0} باید حداقل 2 و حداکثر 100 کاراکتر باشد")]
        public string Description { get; set; }



        [Display(Name = "قیمت")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        public decimal Price { get; set; }


        [Display(Name = "موجودی")]
        public Nullable<int> Inventory { get; set; }



        [Display(Name = "تعداد فروش")]
        public Nullable<int> SalesNumber { get; set; }



        [Display(Name = "تاریخ ثبت نام")]
        public Nullable<System.DateTime> RegisterDate { get; set; }


        [Display(Name = "وضعیت")]
        public Nullable<bool> IsActive { get; set; }



        [Display(Name = "وضعیت موجودی")]
        public Nullable<bool> InventoryStatus { get; set; }



        [Display(Name = "مدیر ثبت کننده")]
        public Nullable<int> RegisterAdminId { get; set; }

        [Display(Name = "آیدی دسته بندی")]
        public Nullable<int> CategoryId { get; set; }


        [Display(Name = "تصویر")]
        public string ImageName { get; set; }
    
        public virtual T_Admins T_Admins { get; set; }
        public virtual T_Categories T_Categories { get; set; }
    }
}
