//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class T_Users
    {
        [Display(Name = "آیدی")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        public int Id { get; set; }



        [Display(Name = "نام")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        [StringLength(20, MinimumLength = 2, ErrorMessage = " {0} باید حداقل 2 و حداکثر 20 کاراکتر باشد")]
        public string Name { get; set; }


        [Display(Name = "نام خانوادگی")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = " {0} باید حداقل 2 و حداکثر 30 کاراکتر باشد")]
        public string Family { get; set; }


        [Display(Name = "شماره همراه")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        [RegularExpression("(09)[0-9]{9}", ErrorMessage = "فرمت شماره همراه اشتباه است")]
        public string PhoneNumber { get; set; }


        [Display(Name = "رمز عبور")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        [DataType(DataType.Password)]
        [StringLength(20, MinimumLength = 2, ErrorMessage = " {0} باید حداقل 2 و حداکثر 20 کاراکتر باشد")]
        public string Password { get; set; }


        [Display(Name = "ایمیل")]
        [EmailAddress(ErrorMessage = "فرمت ایمیل شما اشتباه است")]
        public string Email { get; set; }


        [Display(Name = "کد ملی")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        [RegularExpression("[0-9]{10}", ErrorMessage = "فرمت کد ملی اشتباه است")]
        public string NationalCode { get; set; }


        [Display(Name = "تاریخ ثبت نام")]
        [DisplayFormat(DataFormatString = "{0: dddd, dd MMMM yyyy}")]
        public System.DateTime RegisterDate { get; set; }


        [Display(Name = "وضعیت")]
        public Nullable<bool> IsActive { get; set; }


        [Display(Name = " تصویر")]
        public string ImageName { get; set; }



        [Display(Name = " نقش کاربری")]
        public Nullable<byte> RoleId { get; set; }
    

        public virtual T_Roles T_Roles { get; set; }
    }
}
